### ISSUE TITLE
Width/Height metadata fields

### ISSUE THREAD

**Issue by SkyTheCodeMaster** [SkyTheCodeMaster/bimg#3]
As title implies, should the format include width/height fields? This can be used for integrity checking, and probably some other things.

**Comment by ShreksHellraiser** [comment]
So are these going to be required fields? These can be inferred from the first frame, and will require modifications to be made to existing software to support the 1.0.0 release of the format (if it is made mandatory).

**Comment by SkyTheCodeMaster** [comment]
No, they're going to be optional like all the rest.

**Comment by ShreksHellraiser** [comment]
Then I don't see any reason not to add it, as long as there's a disclaimer that not all images will contain that metadata.

**Comment by SkyTheCodeMaster** [comment]
I looked, and there's actually no disclaimer anywhere.
Even though every single (spare 1-3) one is optional lol
